project_2/force-app/main/default/objects/composite_orders__c/composite_orders__c.object-meta.xml
<CustomObject>
    <label>composite orders</label>
    <nameField>
        <label>composite orders</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>composite orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

project_2/force-app/main/default/objects/composite_orders__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

project_2/force-app/main/default/classes/CompositeOrderBatchToDelete.cls
public class CompositeOrderBatchToDelete implements Database.Batchable<Sobject> {
    public Database.QueryLocator start(Database.BatchableContext bc)
    {
         Date thirtyDaysAgo = Date.today().addDays(-30);
        String query = 'SELECT Id FROM composite_orders__c WHERE CreatedDate< :thirtyDaysAgo AND Status__c != \'Failed\'';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc,List<composite_orders__c> scope)
    {
        delete scope;
    }	
    public void finish(Database.BatchableContext bc)
    {
      system.debug('Batch Job successfully ran');  
    }
}